[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""

[context.deploy-preview.environment]
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""

[context.branch-deploy.environment]
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""
